-- Seed the initial 6 products. Idempotent via ON CONFLICT.

INSERT INTO products (id, name, category, price, old_price, description, badge, color) VALUES
(1,
 'Mini Deshumidificador Smart',
 'Hogar tropical',
 39,
 55,
 'Compacto para closets, dormitorios y apartamentos con humedad alta.',
 'Mas vendido',
 'from-emerald-100 to-cyan-100'),
(2,
 'Ventilador Portatil USB',
 'Calor y movilidad',
 24,
 NULL,
 'Bateria recargable para transporte, oficina, playa y viajes cortos.',
 'Entrega rapida',
 'from-sky-100 to-blue-100'),
(3,
 'Botella Termica 1L',
 'Vida diaria',
 29,
 36,
 'Mantiene bebidas frias durante el dia en clima caliente y humedo.',
 'Eco choice',
 'from-lime-100 to-emerald-100'),
(4,
 'Organizador Anti-Humedad',
 'Casa y closet',
 18,
 NULL,
 'Set para proteger ropa, zapatos y bolsos durante temporada lluviosa.',
 'Pack familiar',
 'from-amber-100 to-orange-100'),
(5,
 'Mochila Impermeable Urbana',
 'Trabajo y universidad',
 49,
 65,
 'Protege laptop y accesorios contra lluvia repentina en la ciudad.',
 'Nuevo',
 'from-slate-100 to-zinc-200'),
(6,
 'Kit Frescura Personal',
 'Beauty & care',
 32,
 NULL,
 'Toalla quick-dry, atomizador y pouch para dias de calor intenso.',
 'Bundle',
 'from-rose-100 to-pink-100')
ON CONFLICT (id) DO UPDATE SET
    name        = EXCLUDED.name,
    category    = EXCLUDED.category,
    price       = EXCLUDED.price,
    old_price   = EXCLUDED.old_price,
    description = EXCLUDED.description,
    badge       = EXCLUDED.badge,
    color       = EXCLUDED.color;
